telegram:
  token: "your-token-id"
  chat_id: "your-chat-id"

thresholds:
  cpu: 80  # Soglia percentuale di CPU
  ram: 80  # Soglia percentuale di RAM
  disk: 90  # Soglia percentuale di /home
  disk_2: 80  # Soglia percentuale di /data

repeat_threshold: 5  # Soglia di messaggi consecutivi
interval: 15  # Intervallo di monitoraggio in secondi
